export HADOOP_HEAPSIZE=2000
export HADOOP_NAMENODE_OPTS="-Xmx5g $HADOOP_NAMENODE_OPTS"
export HADOOP_SECONDARYNAMENODE_OPTS="-Xmx5g $HADOOP_SECONDARYNAMENODE_OPTS"
export HADOOP_DATANODE_OPTS="-Xmx2g $HADOOP_DATANODE_OPTS"
